### PR TITLE
update Japanese translation of avidemux_ja.ts

### PR DESCRIPTION
**Pull request by jw-shin1abe**
Hello,
I updated Japanese translation of avidemux_ja.ts.
Since this is my first use of git-web and PR system, if there are some problem please let me know.
Sorry my poor English.

### CODE REVIEW

**Comment by eumagga0x2a** [comment]
Thank you very much for the update.

**Comment by jw-shin1abe** [comment]
Not, at all. 
I am the one who should thank you.
If I found miss-translation parts on my translation, I will correct it and re-enter PR.

**Comment by adem4ik** [comment]
@jw-shin1abe btw you can test your translation inside the app before making a PR. Here is an example for Windows OS: 
- get the latest nightly build from https://www.avidemux.org/nightly/vsWin64/
- release (convert) your .ts file to .qm using Qt Linguist https://github.com/thurask/Qt-Linguist/releases
- replace avidemux_ja.qm inside \Avidemux\qt5\i18n

**Comment by jw-shin1abe** [comment]
Hi, Andrei 

Thanks for your advice.
OK, I will do pre-check of my translation according to your advice.

JW

**Pull request merged**
