### PR TITLE
Fixed mistranslations (2024-03-16)

### PR DESCRIPTION
**Pull request by jw-shin1abe**
Fixed mistranslated parts of Conversion status dialog.
1. source -- Phase:
    translation OLD --  位相:
    translation NEW -- 状態:

2. source -- Less than a minute
    translation OLD -- 分未満
    translation NEW -- １分以下

### CODE REVIEW

**Comment by jw-shin1abe** [comment]
Sorry.  
avidemux_ja.ts of my local master was still old.
The correct diff of avidemux_ja.ts is below.
=================================
--- avidemux_2.8.2.c30c468/avidemux/qt4/i18n/avidemux_ja.ts	2024-03-16 09:57:10.996005802 +0900
+++ avidemux_2.8.2.c30c468.New/avidemux/qt4/i18n/avidemux_ja.ts	2024-03-16 10:09:11.328729526 +0900
@@ -3736,7 +3736,7 @@
     <message>
         <location filename="../../../avidemux_core/ADM_core/src/ADM_prettyPrint.cpp" line="-2"/>
         <source>Less than a minute</source>
-        <translation>分未満</translation>
+        <translation>１分以下</translation>
     </message>
     <message>
         <location filename="../../common/ADM_commonUI/myOwnMenu.h" line="-28"/>
@@ -6752,7 +6752,7 @@
     <message>
         <location line="-103"/>
         <source>Phase:</source>
-        <translation>位相:</translation>
+        <translation>状態:</translation>
     </message>
     <message>
         <location line="+475"/>
====================================

**Comment by eumagga0x2a** [comment]
I'm sorry for the delay, I'm stuck in limbo waiting for a new VC++ nightly build to happen ([or to fail](https://github.com/mean00/avidemux2/commit/ab13a3b71c86da642fdc7c43df0cf3fae8f697a8)) off the same git revision as other nightlies to keep them in sync when possible.

Could you please open a new pull request for the very same changes but without merge commits?

I'll pull it as soon as the unclear situation with VC++ node is resolved.

**Comment by jw-shin1abe** [comment]
Hi, Euma
Thank you for your reply.

Since I'm not familiar with GIT system, I have no idea how to "open a new pull request for the very same changes but without merge commits".
The focus of my question is "but without merge commits".

Sorry for my poor experience.


On Fri, 22 Mar 2024 16:05:25 -0700
eumagga0x2a ***@***.***> wrote:

> I'm sorry for the delay, I'm stuck in limbo waiting for a new VC++ nightly build to happen ([or to fail](https://github.com/mean00/avidemux2/commit/ab13a3b71c86da642fdc7c43df0cf3fae8f697a8)) off the same git revision as other nightlies to keep them in sync when possible.
> 
> Could you please open a new pull request for the very same changes but without merge commits?
> 
> I'll pull it as soon as the unclear situation with VC++ node is resolved.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mean00/avidemux2_i18n/pull/46#issuecomment-2016064371
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
JW (ABE Shin-ichi ) ***@***.***>

**Comment by eumagga0x2a** [comment]
Nevermind, thank you very much for the fix.

**Pull request merged**
